### ISSUE TITLE
Height, width not set in level 0

### ISSUE THREAD

**Issue by jonasteuwen** [amspath/libisyntax#14]
In the function [isyntax_init_level_offsets](https://github.com/amspath/libisyntax/blob/68400c321ff7f59b9ae80f0663ed802b18cb3984/src/isyntax/isyntax.c#L2725), I believe in level 0 we also need to set `width` and `height`, so perhaps we can set them (otherwise `libisyntax_level_get_width` and `libisyntax_level_get_height` will return 0.

In my experiment with an isyntax file, it looked like that there is an offset in level 0 as well.

**Comment by Falcury** [comment]
Ok, I’ll look into this tomorrow.

**Comment by Falcury** [comment]
I fixed this in b837f88c44bb3126a33a7ad17d7e65a237a43902.
I also moved the initialization of these values to a more appropriate place in `isyntax_open()`.

**Comment by jonasteuwen** [comment]
Great! I will verify with a few samples, and also check when written to .tiff if it matches the SDK pixels.

**Comment by Falcury** [comment]
I've noticed in the past that TIFF files converted from iSyntax using the SDK (not IMS export) have their offsets shifting between levels. So that might also be a source of problems.

To make the shift between levels more easily visible I added a debug slider to Slidescape, see the screenshot below:

![image](https://user-images.githubusercontent.com/8642739/233627148-f497793a-ab70-4d7e-b303-fb1e8c971e3a.png)

You could also use this to verify that the level offsets we are calculating for iSyntax are (visually) correct.

**Comment by jonasteuwen** [comment]
That's great! Will use it.

**Comment by jonasteuwen** [comment]
@Falcury It's very useful thanks! 

If I use this and convert the tiff according to my read_region, it's very jumpy and it doesn't look like the offset is correct in `origin_offset_in_pixels`. If I use `int32_t offset = ((PER_LEVEL_PADDING << level_count) - PER_LEVEL_PADDING) >> level;`, this does not (really) happen, but then there appears to be an absolute offset compared with the Philips SDK.

There is a very minor shift when you use the offset I'm giving, but for the currently defined one from level 3 onwards it really shifts

**Comment by jonasteuwen** [comment]
Check #17, I think the formula given by me is correct

**Comment by jonasteuwen** [comment]
Seems to be addressed.

**Comment by Falcury** [comment]
I had to revert to storing the height/width of the WSI including the padding, because this affects the calculation of the grid width and height. This was causing some codeblocks to not get initialized, leading to a crash on some iSyntax files (specifically, the example image 3.isyntax that was provided by Philips on their original OpenPathology portal).
I added and renamed new width/height fields with the padding subtracted.
Commit: https://github.com/amspath/libisyntax/commit/5acc98b68e6ac253cec4f2afdea65a314ef26b62

**Comment by jonasteuwen** [comment]
Great catch! Aren’t the names not becoming a bit…ugly?

**Comment by Falcury** [comment]
> Great catch! Aren’t the names not becoming a bit…ugly?

Well, yes they are, but I figured I had to make a descriptive distinction somehow ;-) How would you name them?
I figured it would be OK to rename these values to something else, also because they're hidden behind a getter in the public API...

**Comment by jonasteuwen** [comment]
Perhaps, since they actually are the height and width of the image itself, it could be level_height, or height and rename the others?

**Comment by Falcury** [comment]
> Perhaps, since they actually are the height and width of the image itself, it could be level_height, or height and rename the others?

@jonasteuwen Done: https://github.com/amspath/libisyntax/commit/6a597e1d56d82d8db78ea497c95c865a4ebe015d

**Comment by jonasteuwen** [comment]
Great, seems to be doing what we need!
