### ISSUE TITLE
Wsi image index?

### ISSUE THREAD

**Issue by erikogabrielsson** [amspath/libisyntax#38]
Hi,

What is the purpose of the `libisyntax_get_wsi_image_index`-method and the `wsi_image_index`-parameter to the `libisyntax_get_image`-method?

**Comment by alex-virodov** [comment]
The purpose is to allow access to the `wsi_image` pointer which allows access to all the interesting things like level resolutions etc. 

The reason we have that indirection instead of e.g. `libisyntax_get_wsi_image(..)` is mostly historical - there was `libisyntax_get_macro/label_image_index(..)`, but we opted to have more specific methods to access the macro/label images - `libisyntax_read_macro/label_image(..)`. This is because they have different specifics - no levels, and no need for fancy access patterns - they are usually just read in full.

It probably would be best to replace `libisyntax_get_image(isyntax, index)` with `libisyntax_get_wsi_image(isyntax)` and get rid of the `.._index` method.

Hope that helps.

**Comment by Falcury** [comment]
> It probably would be best to replace `libisyntax_get_image(isyntax, index)` with `libisyntax_get_wsi_image(isyntax)` and get rid of the `.._index` method.

Agreed!

Edit: done in https://github.com/amspath/libisyntax/commit/8a2378656424643761075bddea7e17b02b9764cb
